"""
Django settings for powermoniter project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys

from pathlib import Path
from django.utils import timezone

from dotenv import load_dotenv
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# 加载环境变量
load_dotenv()

# 指定要加载的配置文件路径
load_dotenv('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--_#pmj7sv3wc8r#7fhc^c!3$!*(&(mcuyq2w-lm(x!!%2!z7oj'

# SECURITY WARNING: don't run with debug turned on in production!
def get_bool_env(var_name: str, default: bool = False) -> bool:
    value = os.getenv(var_name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")

DEBUG = get_bool_env('DEBUG', False)

# 从环境变量读取ALLOWED_HOSTS，如果没有则使用默认值
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else [
    # mengdie.ai 域名系列
    'mengdie.info',
    # 'www.mengdie.ai',
    'api.mengdie.info',

    # 本地开发
    'localhost',
    '127.0.0.1',
    '0.0.0.0',

    # 服务器IP
    '81.68.79.234',
    '47.237.84.36',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 自定义应用
    'apps.repositories',
    'apps.api',

    # 第三方应用
    'corsheaders',
]

# todo 晚点改中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 启用CORS中间件
    'utils.middleware.ConditionalSessionMiddleware',  # 条件性Session，仅Admin使用
    'django.middleware.common.CommonMiddleware',
    'utils.csrf_middleware.ApiCsrfExemptMiddleware',  # API CSRF豁免
    'utils.csrf_middleware.SmartCsrfViewMiddleware',  # 智能CSRF保护（admin等需要）
    'utils.middleware.ConditionalAuthMiddleware',  # 条件性认证，仅Admin使用
    'utils.middleware.ConditionalMessageMiddleware',  # 条件性消息，仅Admin使用
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'powermoniter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'powermoniter.wsgi.application'

# ASGI应用配置
ASGI_APPLICATION = 'powermoniter.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 检查是否在运行测试
TESTING = 'test' in sys.argv or 'pytest' in sys.modules or any('test' in arg for arg in sys.argv)

if TESTING:
    # 测试环境：使用SQLite内存数据库（极速测试，自动清理）
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': ':memory:',
    #         'OPTIONS': {
    #             'timeout': 20,
    #         },
    #         'TEST': {
    #             'NAME': ':memory:',
    #         },
    #     }
    # }
    # print("🧪 测试模式：使用SQLite内存数据库")
    # 测试环境：默认使用PostgreSQL测试数据库（与生产环境一致）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'powermoniter_test',
            'USER': 'postgres',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '5432',
            'OPTIONS': {
                'sslmode': 'disable',  # 测试环境不需要SSL
            },
            'TEST': {
                'NAME': os.environ.get('UNIT_TESTING_DB_NAME', f'unit_testing_{timezone.now().strftime("%Y%m%d_%H%M%S")}'),
                'DEPENDENCIES': [],  # 避免旧连接
                'SERIALIZE': True,   # 启用序列化，确保测试隔离
            },
        }
    }
    print("🐘 测试模式：使用PostgreSQL测试数据库")
else:
    # 开发和生产环境：使用Neon PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),  # Neon数据库需要SSL
                # 关键设置
                # "channel_binding": "require",  # Neon数据库需要
            },
            'CONN_MAX_AGE': 60,  # 连接复用, 连接保持60秒
            # 启用连接健康检查(启用CONN_HEALTH_CHECKS,Django会自动检测连接是否已断开,避免connection failed)
            'CONN_HEALTH_CHECKS': False,  # 不能使用，否则Neon PG的compute一直计费
        }
    }
    if DEBUG:
        print("🐘 开发模式：使用Neon PostgreSQL数据库")
    else:
        print("🚀 生产模式：使用Neon PostgreSQL数据库")

    if 'celery' in sys.argv or 'worker' in sys.argv or 'beat' in sys.argv:
      # Celery worker: 任务间隔较长，关闭健康检查
      DATABASES['default']['CONN_HEALTH_CHECKS'] = False
      DATABASES['default']['CONN_MAX_AGE'] = 0  # 任务完成后立即关闭连接
    else:
      # Web应用: 访问频繁，可以承受健康检查成本
      DATABASES['default']['CONN_HEALTH_CHECKS'] = True
      DATABASES['default']['CONN_MAX_AGE'] = 120  # 2分钟复用

# 自定义用户模型
AUTH_USER_MODEL = 'repositories.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS设置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:9000",
    "http://127.0.0.1:9000",
    "http://81.68.79.234",
    "http://47.237.84.36",
    "http://localhost:5173",
    "https://api.mengdie.info",
    "https://9aeae6d4.powermoniter-frontend.pages.dev",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF设置 - 前后端分离友好配置
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:9000",
    "http://127.0.0.1:9000",
    "http://81.68.79.234",
    "http://47.237.84.36",
    "http://localhost:5173",
    "https://api.mengdie.info",
    "https://9aeae6d4.powermoniter-frontend.pages.dev",
]

# API接口CSRF豁免URL模式
CSRF_EXEMPT_URLS = [
    r'^api/',  # 所有以api/开头的路径
    r'^admin/',  # admin后台也豁免（临时解决方案）
    r'^static/',   # 静态文件豁免CSRF检查
    r'^media/',    # 媒体文件豁免CSRF检查
]

# CSRF Cookie设置 - 适配HTTPS和前后端分离
CSRF_COOKIE_SECURE = False  # 仅在HTTPS下传输
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问（前端可能需要）
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # 使用cookie而不是session存储CSRF token


# 代理相关设置 - 适配Caddy反向代理
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# 会话设置 - 仅Admin使用
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 日志设置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# JWT相关配置（用于用户认证）
JWT_SECRET = SECRET_KEY  # JWT加密密钥，建议使用独立的密钥
JWT_ALGORITHM = "HS256"  # JWT加密算法
JWT_EXP_DELTA_HOURS = 12  # JWT有效期12小时
