# Generated by Django 5.2.8 on 2025-11-12 08:58

import apps.repositories.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('pw_fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='输入密码错误次数')),
            ],
            options={
                'db_table': 'account_user',
            },
            managers=[
                ('objects', apps.repositories.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(max_length=200, verbose_name='设备所在地方')),
                ('mac', models.CharField(max_length=12, unique=True)),
                ('broker', models.CharField(max_length=100, verbose_name='服务器地址')),
                ('port', models.PositiveSmallIntegerField(default=1883)),
                ('pub_topic', models.CharField(max_length=100, verbose_name='发布主题')),
                ('sub_topic', models.CharField(max_length=100, verbose_name='订阅主题')),
                ('client_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, verbose_name='用户名参数')),
                ('password', models.CharField(max_length=100, verbose_name='密码参数')),
                ('status', models.BooleanField(choices=[(1, 'enabled'), (0, 'disabled')], default=apps.repositories.models.DeviceStatus['ENABLED'])),
                ('collect_enabled', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('ingress_type', models.BooleanField(choices=[(0, 'mqtt'), (1, 'tcp')], default=apps.repositories.models.IngressType['MQTT'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=12, null=True)),
                ('raw_payload', models.JSONField()),
                ('failure_reason', models.CharField(max_length=255)),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
                ('retryable', models.BooleanField(default=False)),
                ('meta', models.JSONField(null=True)),
                ('device', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='repositories.device')),
            ],
            options={
                'db_table': 'dead_letter',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('mac', models.CharField(db_index=True, max_length=12, verbose_name='设备 MAC')),
                ('last_envelope_ts', models.DateTimeField(null=True, verbose_name='最近一次处理的消息时间戳')),
                ('cursor', models.CharField(max_length=128, null=True, verbose_name='自定义游标（比如 MQTT 消息 ID、TCP 偏移量等）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='进度更新时间')),
                ('device', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='repositories.device')),
            ],
            options={
                'db_table': 'subscription_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12)),
                ('ts', models.DateTimeField(blank=True, null=True, verbose_name='记录时间')),
                ('energy_kwh', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='累计用电量，单位KW*H，保留三位小数，断电后不会归零，重置后会归零')),
                ('power', models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='当前功率，单位W，保留三位小数')),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='当前电压，单位V，保留三位小数')),
                ('current', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='当前电流，单位A，保留三位小数')),
                ('key', models.CharField(max_length=64, null=True, verbose_name='设备通断电状态，0：断电，1：通电')),
                ('payload', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('device', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='repositories.device')),
            ],
            options={
                'db_table': 'reading',
                'indexes': [models.Index(fields=['device', 'ts'], name='reading_device__87efdf_idx')],
                'unique_together': {('mac', 'ts', 'payload_hash')},
            },
        ),
    ]
